# Generated by Django 2.2.10 on 2021-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(default=0)),
                ('project_name', models.CharField(max_length=20)),
                ('project_desc', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
