# Generated by Django 3.2.3 on 2021-06-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id_feature', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('user_story', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='scenario',
            fields=[
                ('id_scenario', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id_condition', models.AutoField(primary_key=True, serialize=False)),
                ('tipe', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenario')),
            ],
        ),
    ]
