# Generated by Django 2.2.10 on 2021-06-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210610_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='user_story',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_action',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_actor',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_benefit',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
